export const projects = [
  {
    title: 'Minesweeper',
    description: "This version of Minesweeper was created using vanilla Javascript and follows a recursive algorithm",
      image: '/images/pic6.png',
      tags: ['HTML', 'JavaScript'],
    source: 'https://github.com/SenuraJayasinghe/Minesweeper',
    visit: 'https://minesweeper-bice.vercel.app/',
    id: 0,
  },
  {
    title: 'Pac-Man',
    description: "This version of Pac-Man was created using vanilla Javascript and contains background sound effects.",
    image: '/images/pic5.png',
    tags: ['HTML', 'JavaScript'],
    source: 'https://github.com/SenuraJayasinghe/Pacman',
    visit: 'https://pacman-sandy.vercel.app/',
    id: 1,
  },
  {
    title: 'Covid19 tracker',
    description: "Created using Vue3, this tracker uses covid19api to displays the new/total cases and deaths globaly as well as per country",
      image: '/images/pic1.png',
      tags: ['Vue.js', 'Tailwind CSS','Covid19api'],
    source: 'https://github.com/SenuraJayasinghe/Covid-Tracker',
    visit: 'https://covid-tracker-livid-tau.vercel.app/',
    id: 2,
  },
  {
    title: 'IP Address Tracker',
    description: "Created using Vue3, this app uses ip geolocation api to locate the searched IP address and show its location on the map",
    image: '/images/pic2.png',
    tags: ['Vue.js' , 'Leaflet.js', 'Tailwind CSS', 'Mapbox API'],
    source: 'https://github.com/SenuraJayasinghe/IP-Address-Tracker',
    visit: 'https://ip-adress-tracker-beige.vercel.app/',
    id: 3,
  },
  {
    title: 'Alan AI News App',
    description: "Created using the Alan AI speech recognition software, allowing users to control the app using their voice",
    image: '/images/pic3.png',
    tags: ['React', 'Alan AI', 'Material UI'],
    source: 'https://github.com/SenuraJayasinghe/alan-ai-news-app',
    visit: 'https://alan-ai-news-app-rho.vercel.app/',
    id: 3,
  },
  {
    title: 'Daily Planner',
    description: "Created using mern stack, lets users create accounts to enter their daily tasks",
    image: '/images/pic4.png',
    tags: ['MongoDB', 'Express', 'React', 'Node'],
    source: 'https://github.com/SenuraJayasinghe/Daily-Planner',
    visit: 'https://dailyplannersenura.herokuapp.com/login',
    id: 3,
  },
  {
    title: 'Green Task Force',
    description: "This multi functional app lets users create accounts and pin their location on a map with details for garbage removal",
    image: '/images/pic7.png',
    tags: ['JavaScript', 'PHP', 'Bootstrap'],
    source: 'https://github.com/SenuraJayasinghe/Green-Task-force',
    visit: '',
    id: 3,
  },
  {
    title: 'New York Times App',
    description: "This App shows the latest news on various headlines such as travel, politics and science provided by the New York times",
    image: '/images/pic8.png',
    tags: ['Vue.js', 'Tailwind CSS', 'NYTimes Lastest News API'],
    source: 'https://github.com/SenuraJayasinghe/nytimesapi-vue',
    visit: 'https://nytimesapi-vue.vercel.app/',
    id: 3,
  },
];

