export const projects = [
  {
    title: 'Minesweeper',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
      image: '/images/pic6.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/SenuraJayasinghe/Minesweeper',
    visit: 'https://minesweeper-bice.vercel.app/',
    id: 0,
  },
  {
    title: 'Pacman',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    image: '/images/pic5.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/SenuraJayasinghe/Pacman',
    visit: 'https://pacman-sandy.vercel.app/',
    id: 1,
  },
  {
    title: 'Covid19 tracker',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/pic1.png',
      tags: ['React', 'WebRTC'],
    source: 'https://github.com/SenuraJayasinghe/Covid-Tracker',
    visit: 'https://covid-tracker-livid-tau.vercel.app/',
    id: 2,
  },
  {
    title: 'IP Address Tracker',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/pic2.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/SenuraJayasinghe/IP-Address-Tracker',
    visit: 'https://ip-adress-tracker-beige.vercel.app/',
    id: 3,
  },
  {
    title: 'Alan AI News App',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/pic3.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/SenuraJayasinghe/alan-ai-news-app',
    visit: 'https://alan-ai-news-app-rho.vercel.app/',
    id: 3,
  },
  {
    title: 'Daily Planner',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/pic4.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://dailyplannersenura.herokuapp.com/login',
    id: 3,
  },
];

